/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_clover_car_TaskThread */

#ifndef _Included_com_clover_car_TaskThread
#define _Included_com_clover_car_TaskThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_clover_car_TaskThread
 * Method:    doTask
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_clover_car_TaskThread_doTask
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_clover_car_TaskThread
 * Method:    stopTask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_clover_car_TaskThread_stopTask
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
